version: '3'
services:
  mongo:
    environment:
      MONGO_ADMIN_PASSWORD: $MONGO_ADMIN_PASSWORD
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DB: $MONGO_DB
      MONGO_CONF_PATH: /mongo-conf/mongod.conf
    image: patrickosborne/mongo
    restart: "no"
    volumes:
      - /Users/ozzy/osoft/docker/mongo/mongod.conf:/mongo-config/mongod.conf
    ports:
      - 27017:27017
    logging:
      options:
        max-size: "5m"
        max-file: "10"

  mongo-persisted:
    environment:
      MONGO_ADMIN_PASSWORD: $MONGO_ADMIN_PASSWORD
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DB: $MONGO_DB
      MONGO_CONF_PATH: /mongo-conf/mongod.conf
    image: patrickosborne/mongo
    restart: "no"
    volumes:
      - /data/mongo/$MONGO_DB:/data/db
      - /Users/ozzy/osoft/docker/mongo/mongod.conf:/mongo-config/mongod.conf
    ports:
      - 27017:27017
    logging:
      options:
        max-size: "5m"
        max-file: "10"